apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: c9odx5onh-nodejs 
  janus-idp.io/tekton: c9odx5onh-nodejs
  backstage.io/kubernetes-id: c9odx5onh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c9odx5onh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml